codium --install-extension dbaeumer.vscode-eslint
codium --install-extension bmalehorn.vscode-fish
codium --install-extension sysoev.language-stylus
# Color themes
codium --install-extension pkief.material-icon-theme
codium --install-extension muhammad-sammy.gray-theme
codium --install-extension itsjonq.owlet
codium --install-extension enkia.tokyo-night
codium --install-extension vladeeg.vscode-theme-vlight
